# Generated by Django 5.0.4 on 2024-04-20 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wander', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guide',
        ),
    ]
