# Generated by Django 5.0.4 on 2024-04-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wander', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages_known', models.CharField(max_length=100)),
                ('places_known', models.CharField(max_length=100)),
                ('govt_id', models.CharField(max_length=100)),
                ('quiz_score', models.IntegerField()),
            ],
        ),
    ]
