# Generated by Django 5.0.4 on 2024-04-19 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wander', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='user',
        ),
    ]
