# Generated by Django 5.0.4 on 2024-04-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wander', '0002_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='quiz_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
