# Generated by Django 5.0.4 on 2024-04-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wander', '0003_guide_email_alter_guide_quiz_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='email',
        ),
        migrations.AlterField(
            model_name='guide',
            name='quiz_score',
            field=models.IntegerField(),
        ),
    ]
