# Generated by Django 5.0.4 on 2024-04-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wander', '0003_guide_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='govtIdType',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='guide',
            name='govt_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='guide',
            name='languages_known',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='guide',
            name='places_known',
            field=models.CharField(default='', max_length=100),
        ),
    ]
