# Generated by Django 5.0.4 on 2024-04-15 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wander', '0004_remove_guide_email_alter_guide_quiz_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='guide', to='Wander.user'),
        ),
    ]
