# Generated by Django 5.0.4 on 2024-04-15 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wander', '0005_guide_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guide', to='Wander.user'),
        ),
    ]
