# Generated by Django 5.0.4 on 2024-04-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wander', '0005_visitplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='govtIdType',
            field=models.CharField(choices=[('PAN', 'PAN Card'), ('Aadhar', 'Aadhar Card')], max_length=30),
        ),
        migrations.AlterField(
            model_name='guide',
            name='languages_known',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Urdu', 'Urdu'), ('Arabi', 'Arabi'), ('Korean', 'Korean'), ('Japanese', 'Japanese'), ('French', 'French'), ('Spanish', 'Spanish')], max_length=100),
        ),
        migrations.AlterField(
            model_name='guide',
            name='places_known',
            field=models.CharField(choices=[('1', 'Bara Imambara'), ('2', 'Chota Imambara'), ('3', 'Rumi Darwaza'), ('4', 'Lucknow Zoo'), ('5', 'Residency')], max_length=100),
        ),
    ]
