# Generated by Django 5.0.4 on 2024-04-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wander', '0006_alter_guide_govtidtype_alter_guide_languages_known_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='languages_known',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='guide',
            name='places_known',
            field=models.CharField(max_length=100),
        ),
    ]
