# Generated by Django 5.0.4 on 2024-04-21 14:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wander', '0007_alter_guide_languages_known_alter_guide_places_known'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitplan',
            name='insertDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='visitplan',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='visitplan',
            name='isBooked',
            field=models.BooleanField(default=False),
        ),
    ]
