# Generated by Django 5.0.4 on 2024-04-22 07:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wander', '0008_visitplan_insertdatetime_visitplan_isactive_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateBit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insert_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('visit_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wander.visitplan')),
            ],
        ),
    ]
