# Generated by Django 5.0.4 on 2024-04-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wander', '0009_ratebit'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitplan',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitplan',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitplan',
            name='modeOfPayment',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online')], default='Cash', max_length=10),
        ),
    ]
