# Generated by Django 5.0.4 on 2024-04-15 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wander', '0009_alter_guide_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guide',
        ),
    ]
