# Generated by Django 5.0.4 on 2024-04-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wander', '0013_alter_visitplan_modeofpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitplan',
            name='modeOfPayment',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online')], default='none', max_length=10),
        ),
    ]
