# Generated by Django 5.0.4 on 2024-04-18 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wander', '0020_alter_guide_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='languages_known',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='guide',
            name='places_known',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='guide',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guide', to=settings.AUTH_USER_MODEL),
        ),
    ]
