# Generated by Django 5.0.4 on 2024-04-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wander', '0021_alter_guide_languages_known_alter_guide_places_known_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='quiz_score',
            field=models.IntegerField(default=1),
        ),
    ]
