# Generated by Django 5.0.4 on 2024-04-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wander', '0022_alter_guide_quiz_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='languages_known',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='guide',
            name='places_known',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='guide',
            name='quiz_score',
            field=models.IntegerField(default=0),
        ),
    ]
