# Generated by Django 5.0.4 on 2024-04-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wander', '0023_alter_guide_languages_known_alter_guide_places_known_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='languages_known',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='places_known',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
