# Generated by Django 5.0.4 on 2024-04-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wander', '0024_alter_guide_languages_known_alter_guide_places_known'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='languages_known',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guide',
            name='places_known',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
