# Generated by Django 5.0.4 on 2024-04-18 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wander', '0025_alter_guide_languages_known_alter_guide_places_known'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guide',
        ),
    ]
